# Generated by Django 5.0.7 on 2024-07-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projecttasks_options_remove_projecttasks_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='projects/images/'),
        ),
        migrations.AddField(
            model_name='projecttasks',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='projects/images/'),
        ),
    ]
